ARCHIVO_CLIENTES = 'clientes.txt'
ARCHIVO_LIBROS = 'libros.txt'

ESTADO_CLIENTE_LIBRE = 'L'
ESTADO_CLIENTE_OCUPADO = 'O'
ESTADO_CLIENTE_ELIMINADO = 'B'
ESTADO_LIBRO_LIBRE= 'D'
ESTADO_LIBRO_OCUPADO = 'P'

NULL = ''
